import type { Metadata } from "next";
import { Newsreader, Manrope, Geist } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { cn } from "@/lib/utils";
import { StackProvider, StackTheme } from "@stackframe/stack";
import { stackServerApp } from "@/stack/server";
const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

const newsreader = Newsreader({
    variable: "--font-newsreader",
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"],
});

const manrope = Manrope({
    variable: "--font-manrope",
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={cn(
                "h-full",
                "antialiased",
                manrope.variable,
                newsreader.variable,
                "font-sans",
                geist.variable,
            )}
            suppressHydrationWarning
        >
            <body className="min-h-full flex flex-col">
                <StackProvider app={stackServerApp}>
                    <StackTheme>                       
                        <Header />
                        {children}
                        <Footer />
                    </StackTheme>
                </StackProvider>
            </body>
        </html>
    );
}
